Run a force-bump with dev-preview2
openstack-k8s-operators/openstack-operator pull request #509
Opened 2023-10-10 20:45 UTC by dprince

2023-10-11 06:09 UTC, stuggi commented
`Error: Project github.com/openstack-k8s-operators/designate-operator does not have the default branch master`
wondering why this is happening. designate is not yet integrated

2023-10-16 12:27 UTC, stuggi commented
recheck

2023-10-26 16:22 UTC, rebtoor commented
recheck

2023-11-10 11:07 UTC, rebtoor commented
recheck

2023-11-10 15:04 UTC, rebtoor requested changes

2023-11-10 15:04 UTC, rebtoor commented on apis/go.mod
> +	github.com/openstack-k8s-operators/placement-operator/api v0.3.0
same as above

2023-11-10 15:04 UTC, rebtoor commented on apis/go.mod
> +	github.com/openstack-k8s-operators/swift-operator/api v0.3.0
same as above

2023-11-10 15:04 UTC, rebtoor commented on apis/go.mod
> +	github.com/openstack-k8s-operators/lib-common/modules/openstack v0.1.1-0.20231001084618-12369665b166 //indirect
`v0.2.0` ?

2023-11-10 15:04 UTC, rebtoor commented on apis/go.mod
> +	github.com/openstack-k8s-operators/cinder-operator/api v0.3.0
Should we call `v0.2.0` here ?

2023-11-10 15:04 UTC, rebtoor commented on apis/go.mod
> +	github.com/openstack-k8s-operators/nova-operator/api v0.3.0
same as above

2023-11-10 15:04 UTC, rebtoor commented on go.mod
> +	github.com/openstack-k8s-operators/cinder-operator/api v0.3.0
`v0.2.0` ?

2023-11-10 15:04 UTC, rebtoor commented on go.mod
> +	github.com/openstack-k8s-operators/nova-operator/api v0.3.0
`v0.2.0` ?

2023-11-10 15:04 UTC, rebtoor commented on go.mod
> +	github.com/openstack-k8s-operators/openstack-baremetal-operator/api v0.3.1-0.20231005142619-75b1fbd8777c
`v0.2.0` ?

2023-11-10 15:04 UTC, rebtoor commented on go.mod
> +	github.com/openstack-k8s-operators/placement-operator/api v0.3.0
`v0.2.0`?

2023-11-10 15:04 UTC, rebtoor commented on go.mod
> +	github.com/openstack-k8s-operators/swift-operator/api v0.3.0
`v0.2.0`?

2023-11-10 15:04 UTC, rebtoor commented on go.mod
> +	github.com/openstack-k8s-operators/lib-common/modules/openstack v0.1.1-0.20231001084618-12369665b166 //indirect
`v0.2.0`?

2023-11-10 15:05 UTC, merged