Re-enable encrypted volume test
openstack-k8s-operators/openstack-operator pull request #600
Opened 2023-12-13 05:50 UTC by vakwetu

Now that barbican is integrated with cinder and nova, re-enable this test to make sure it still works

2023-12-13 17:09 UTC, ASBishop commented
I don't have experience defining these jobs, but from what I can tell from the logs the controlplane isn't defining any cinder-volume service. You end up with cinder-api and cinder-scheduler but no cinder-volume backend(s). The cinder gang is still (slowly) marching toward support for the LVM backend, which will be handy for CI purposes, but until then we'll need to limit testing volume encryption to a job that includes ceph in order to get a cinder RBD backend.

2024-01-02 22:58 UTC, dprince requested changes
marking changes needed based on feedback

2024-06-11 06:10 UTC, stuggi commented
@vakwetu is this PR still needed?

2024-06-11 13:34 UTC, vakwetu commented
No longer needed.

2024-06-11 13:34 UTC, closed without merging