update operator-sdk to use local/bin
openstack-k8s-operators/openstack-operator pull request #601
Opened 2023-12-13 16:46 UTC by yazug

specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk

2023-12-14 19:50 UTC, yazug commented
/test openstack-operator-build-deploy-kuttl

2023-12-14 21:07 UTC, yazug commented
/test openstack-operator-build-deploy-kuttl

2024-01-02 22:33 UTC, dprince approved these changes

2024-01-02 22:34 UTC, dprince commented
/test openstack-operator-build-deploy-kuttl

2024-01-02 22:38 UTC, dprince commented
recheck

2024-01-04 00:24 UTC, dprince commented
/test openstack-operator-build-deploy-kuttl

2024-01-04 00:24 UTC, dprince commented
recheck

2024-01-04 12:45 UTC, dprince requested changes
@yazug The CI failures here are valid. The updated 'bundle' target needs to have bundle-cache-extra-data re-added to fix it

2024-01-04 12:45 UTC, dprince commented on Makefile
>  .PHONY: bundle
the bundle-cache-extra-data here is needed

2024-01-05 14:43 UTC, yazug commented
recheck

2024-01-11 09:59 UTC, abays commented
recheck

2024-01-15 18:52 UTC, merged